### ISSUE TITLE
API REJECTING Numbers Starting With 2607

### ISSUE THREAD

**Issue by blessedjasonmwanza** [cynojine/cynsms-api#3]
The API currently seems to raise  "{"code":"**103**","message":"**1 invalid Phone Number on your list**"}" error when I use _new Zambia number foumarts_... Is there a work around this?

**Comment by kazashim** [comment]
> The API currently seems to raise "{"code":"**103**","message":"**1 invalid Phone Number on your list**"}" error when I use _new Zambia number foumarts_... Is there a work around this?

Adding New Zambia Number Format
